language: cpp
dist: focal

git:
    submodules: false

compiler:
    - gcc
    - clang

env:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

cache:
    directories:
        boost-cache

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init
    - ln -s ../boost-cache Boost/boost

install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y ninja-build g++-10 clang-10 libpq-dev postgresql-server-dev-all

script:
    - mkdir build.tmp && cd build.tmp
    - 'if [ "$CXX" = "g++" ]; then export CC=gcc-10; export CXX=g++-10; fi'
    - 'if [ "$CXX" = "clang++" ]; then export CC=clang-10; export CXX=clang++-10; fi'
    - cmake .. -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -G Ninja -DSKIP_BUILD_TEST=ON
    - ninja
